language: python
git:
  depth: 3
  submodules: false
python:
  - "2.7"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -e .
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
